services:

  baseapi_db:
    # https://hub.docker.com/_/postgres/
    image: postgres
    restart: unless-stopped
    volumes:
      - baseapi_db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: eligdb
      POSTGRES_USER: sawyer
      POSTGRES_PASSWORD: pizza

volumes:
  baseapi_db_data:
