# NOTE: ${COMPOSE_PROJECT_NAME} can be used to configure the name of the project. The top-level name
#   key does similar things. The default is the compose.yml's containing directory.

# NOTE: a .env in the working dir will be ready, and env vars can be used here in syntax ${VAR}

services:

  # https://hub.docker.com/_/postgres/
  eligdb:
    image: postgres
    restart: always
    ports:
      - "[::1]:5432:5432"
    volumes:
      - eligdb_data:/var/lib/postgresql/data/
      - ./dev/eligdb/:/docker-entrypoint-initdb.d/
    networks:
      - network
    environment:
      POSTGRES_DB: eligdb
      POSTGRES_USER: sawyer
      POSTGRES_PASSWORD: pizza

  # https://www.pgadmin.org/docs/pgadmin4/9.3/container_deployment.html
  # TODO: It'd be slick to auto-sign in and auto-register the eligdb server
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - eligdb
    ports:
      - "[::1]:5050:80"
    networks:
      - network
    environment:
      PGADMIN_DEFAULT_EMAIL: sawyer@fake.com
      PGADMIN_DEFAULT_PASSWORD: pizza

  # You'll need to set <InvariantGlobalization> to false in csproj since Linux or set env var
  # DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false for .NET
  plandb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - "[::1]:1433:1433"
    volumes:
      - plandb_data:/var/opt/mssql/
    networks:
      - network
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Pizza1234!@#$

  # In a more realistic dev env, you'll probably want to use a migrator tool, but this works for
  # Sawyer's local playground, and it's a decent example of initializing a container (although it's
  # always worth considering if an initialization container would be more appropriate).
  reset_plandb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      - plandb
    # This networking mode will allow this container to access plandb on localhost.
    network_mode: service:plandb
    working_dir: /setup
    volumes:
      - ./dev/:/setup/
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Pizza1234!@#$
    command: [ "./reset-mssql-db.sh", "plandb" ]

  # https://mcr.microsoft.com/en-us/artifact/mar/azure-storage/azurite/about
  # https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json&tabs=visual-studio%2Cblob-storage
  # https://github.com/Azure/Azurite
  # TODO: accounts, containers, seed, etc?
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports:
      - "127.0.0.1:10000:10000"
      - "127.0.0.1:10001:10001"
      - "127.0.0.1:10002:10002"
    volumes:
      - azurite_data:/data/
    networks:
      - network

  # TODO: redis? https://hub.docker.com/_/redis

  # TODO: how pull actual (DB) image when debugging?

volumes:
  eligdb_data:
  plandb_data:
  azurite_data:

networks:
  network:
