# NOTE: ${COMPOSE_PROJECT_NAME} can be used to configure the name of the project. The top-level name
#   key does similar things. The default is the compose.yml's containing directory.

# NOTE: a .env in the working dir will be ready, and env vars can be used here in syntax ${VAR}

services:

  # https://hub.docker.com/_/postgres/
  eligdb:
    image: postgres
    restart: always
    ports:
      - "[::1]:5432:5432"
    volumes:
      - eligdb_data:/var/lib/postgresql/data/
      - ./dev/eligdb/:/docker-entrypoint-initdb.d/
    networks:
      - network
    environment:
      POSTGRES_DB: eligdb
      POSTGRES_USER: sawyer
      POSTGRES_PASSWORD: pizza

  # https://www.pgadmin.org/docs/pgadmin4/9.3/container_deployment.html
  # TODO: It'd be slick to auto-sign in and auto-register the eligdb server
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - eligdb
    ports:
      - "[::1]:5050:80"
    networks:
      - network
    environment:
      PGADMIN_DEFAULT_EMAIL: sawyer@fake.com
      PGADMIN_DEFAULT_PASSWORD: pizza

  # You'll need to set <InvariantGlobalization> to false in csproj since Linux or set env var
  # DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false for .NET
  plandb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "[::1]:1433:1433"
    volumes:
      - plandb_data:/var/opt/mssql/
    networks:
      - network
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Pizza1234!@#$

  # In a more realistic dev env, you'll probably want to use a migrator tool, but this works for
  # Sawyer's local playground, and it's a decent example of initializing a container (although it's
  # always worth considering if an initialization container would be more appropriate).
  reset-plandb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      - plandb
    # This networking mode will allow this container to access plandb on localhost.
    network_mode: service:plandb
    working_dir: /setup
    volumes:
      - ./dev/:/setup/
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Pizza1234!@#$
    command: [ "./mssql-db-init.sh", "plandb" ]

  # TODO: redis?

  # TODO: azurite?

  # TODO: how pull actual DB image when debugging?

volumes:
  eligdb_data:
  plandb_data:

networks:
  network:
