# ${COMPOSE_PROJECT_NAME} can be used to configure the name of the project. The top-level name
#   key does similar things. The default is the compose.yml's containing directory.

# A .env in the working dir will be ready, and env vars can be used here in syntax ${VAR}.
#   Also, this file could def stand to make better use of vars, but it's fine.

# There is a top level element `networks` that is very similar to `volumes` (at it is attached to
# specific services very similarly): it allows you to define networks. An example is below. All
# services within the compose project share a default network, so it isn't necessary unless more
# fine-grained network segmentation is desired between services (or if you want to have a network
# driver that isn't bridge).
#networks:
#  shared_network

# TODO: if there's a way to bring down a specific service and destroy it's volume, update the reset
# services to be init-if-empty (setup?) services

# TODO: how pull actual (DB) image when debugging?

services:

  eligdb:
    # https://hub.docker.com/_/postgres/
    image: postgres
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - eligdb_data:/var/lib/postgresql/data/
      - ./compose/eligdb/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: eligdb
      POSTGRES_USER: sawyer
      POSTGRES_PASSWORD: pizza

  pgadmin:
    # https://www.pgadmin.org/docs/pgadmin4/9.3/container_deployment.html
    # TODO: It'd be slick to auto-sign in and auto-register the eligdb server
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - eligdb
    ports:
      - "127.0.0.1:5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: sawyer@fake.com
      PGADMIN_DEFAULT_PASSWORD: pizza

  plandb:
    # You'll need to set <InvariantGlobalization> to false in csproj since Linux or set env var
    # DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false for .NET
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - "127.0.0.1:1433:1433"
    volumes:
      - plandb_data:/var/opt/mssql/
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Pizza1234!@#$

  reset_plandb:
    # In a more realistic dev env, you'll probably want to use a migrator tool, but this works for
    # Sawyer's local playground, and it's a decent example of initializing a container (although it's
    # always worth considering if an initialization container would be more appropriate).
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      - plandb
    # This networking mode will allow this container to access plandb on localhost.
    network_mode: service:plandb
    volumes:
      - ./compose/:/setup/
    working_dir: /setup
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Pizza1234!@#$
    command: [ "./reset-mssql-db.sh", "plandb" ]

  azurite:
    # https://mcr.microsoft.com/en-us/artifact/mar/azure-storage/azurite/about
    # https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json&tabs=visual-studio%2Cblob-storage
    # https://github.com/Azure/Azurite
    # Default account name: devstoreaccount1
    # Default account key: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
    # Default connection string for all Azurite services: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;
    # Default connection string for Azurite blob service: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;
    # Default connection string for Azurite queue service: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;
    # Default connection string for Azurite table service: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;
    # The docs (above) have info on using https connection strings.
    # Recall that adding "/{container_name}" to the end of the blob container URL will drill to that
    #   container specifically.
    # To create more accounts, create env var AZURITE_ACCOUNTS with value "account1:key1;account2:key1:key2"
    #   (where the keys are base 64 encoded). Note that this will disable the default account.
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports:
      # Azure Storage Explorer doesn't play nice with ipv6, so localhost seemingly must used.
      - "127.0.0.1:10000:10000"
      - "127.0.0.1:10001:10001"
      - "127.0.0.1:10002:10002"
    volumes:
      - azurite_data:/data/

  reset_azurite_container_id_card:
    # https://mcr.microsoft.com/en-us/artifact/mar/azure-cli/about
    # https://learn.microsoft.com/en-us/cli/azure/get-started-with-azure-cli?view=azure-cli-latest
    # https://learn.microsoft.com/en-us/cli/azure/?view=azure-cli-latest
    image: mcr.microsoft.com/azure-cli
    depends_on:
      - azurite
    network_mode: service:azurite
    volumes:
      - ./compose/:/setup/
    working_dir: /setup
    environment:
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;
    command: [ "./reset-azurite-container.sh", "id-card" ]

  # TODO: write healthcheck for redis

  redis:
    # https://hub.docker.com/_/redis
    image: redis
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    # The docs suggest that it's possible to have redis create snapshots and to make a volume for
    # those snapshots, but it was being weird, and it's redis, so whatev.

volumes:
  eligdb_data:
  plandb_data:
  azurite_data:
