# NOTE: ${COMPOSE_PROJECT_NAME} can be used to configure the name of the project. The top-level name
#   key does similar things. The default is the compose.yml's containing directory.

# NOTE: a .env in the working dir will be ready, and env vars can be used here in syntax ${VAR}

services:

  psql:
    image: postgres
    restart: always
    ports:
      - "[::1]:5432:5432"
    volumes:
      - psql_data:/var/lib/postgresql/data
    networks:
      - network
    environment:
      POSTGRES_USER: sawyer
      POSTGRES_PASSWORD: pizza
      POSTGRES_DB: eligdb

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "[::1]:5050:80"
    networks:
      - network
    environment:
      PGADMIN_DEFAULT_EMAIL: sawyer@fake.com
      PGADMIN_DEFAULT_PASSWORD: pizza

volumes:
  psql_data:

networks:
  network:

# TODO: redis

# TODO: db migration container?

# TODO: blob?

# TODO: .net dev container?
