services:

  psql:
    image: postgres
    restart: always
    ports:
      - "[::1]:5432:5432"
    volumes:
      - psql_data:/var/lib/postgresql/data
    networks:
      - network
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: eligdb

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "[::1]:5050:80"
    networks:
      - network
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"

volumes:
  psql_data:

networks:
  network:

# TODO: redis

# TODO: db migration container?

# TODO: blob?

# TODO: .net dev container?
