include:
  - ../BaseApi/compose.yml

services:

  idcardapi_db:
    # https://hub.docker.com/_/postgres/
    image: postgres
    restart: unless-stopped
    volumes:
      - idcardapi_db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: eligdb
      POSTGRES_USER: sawyer
      POSTGRES_PASSWORD: pizza
    depends_on:
      - baseapi_db

volumes:
  idcardapi_db_data:
